python compilation failed!

###output:


###error:
Traceback (most recent call last):
  File "/Users/zhaozhaozhaozhao/Unambigious_prompt/exp/output_tb_gen_tb_20250406/22/step2_pychecker.py", line 61, in <module>
    outputs = check_output(cycle)
              ^^^^^^^^^^^^^^^^^^^
  File "/Users/zhaozhaozhaozhao/Unambigious_prompt/exp/output_tb_gen_tb_20250406/22/step2_pychecker.py", line 45, in check_output
    return dut.load(stimulus)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/zhaozhaozhaozhao/Unambigious_prompt/exp/output_tb_gen_tb_20250406/22/step2_pychecker.py", line 35, in load
    Y2, Y4 = _TRUTH_TABLE[key]
             ~~~~~~~~~~~~^^^^^
KeyError: '0000000'


